name: Hello
run-name: Run by @${{github.actor}}
on: push
jobs:
    hello:
        runs-on: ubuntu-latest
        env: 
            ACTOR: ${{github.actor}} 
        steps:
            - run: echo "Hello"
              