name: Hello
on: push
jobs:
    hello:
        runs-on: ubuntu-latest
        env: 
            ACTOR: ${{github.actor}} 
        steps:
            - run: echo "${GITHUB_ACTOR}"
            - run: echo "${ACTOR}"