name: Hello
run-name: Run by @${{github.actor}}
on: push
jobs:
    hello:
        runs-on: ubuntu-latest
        env: 
            ACTOR: ${{github.actor}} 
        steps:
            - run: |
                echo "## Example Title :rocket:" >> "${GitHUB_STEP_SUMMARY}"
                echo "- first line" >> "${GitHUB_STEP_SUMMARY}"
                echo "- second line" >> "${GitHUB_STEP_SUMMARY}"
              