name: Hello
on: push
jobs:
    hello:
        runs-on: ubuntu-latest
        env: 
            ACTOR: ${{github.actor}} 
        steps:
            - run: exit 1
            - run: echo "Hello"
              if: true
              